### ISSUE TITLE
Client certificate support?

### ISSUE THREAD

**Issue by ottob** [unjs/node-fetch-native#87]
### Describe the feature

This was possible in node-fetch using a https.Agent:
```ts
 const agent = new https.Agent({
   cert,
   key,
   keepAlive: true,
   timeout: 3 * 1000,
})
const response = await fetch(url, {
    agent,
    method: 'post',
    ...
```

Is there any way of doing this with this library?

see also: https://github.com/nodejs/node/issues/48977 and https://github.com/nodejs/node/issues/47592

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. Surely you can pass `agent` as an option. Types are missing because there is no spec for it but you can. See this example in nuxt (ofetch uses node-fetch-native under the scenes)

https://github.com/nuxt/nuxt/blob/7b35a1fe4faed49fffe3427a0db4aabae138f4ae/packages/vite/src/runtime/vite-node-shared.mjs#L11
